name: cmip6_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas=2.2.3
  - xarray=2023.7.0
  - s3fs=2023.10.0
  - openpyxl=3.1.2
  - matplotlib-base=3.10.1
  - netcdf4=1.6.5
  - scipy=1.15.2
  - numcodecs=0.13.1
  - zarr=2.16.1
  - libblas=*=*openblas*
  - pip=25.0.1
  - pip:
    - aiobotocore==2.7.0
    - aiohttp==3.11.16
    - botocore==1.31.64